### ISSUE TITLE
Add a way to change the default answers of a PE install without specifying a whole new answers file

### ISSUE THREAD

**Issue by Grace-Andrews** [oscar-stack/vagrant-pe_build#88] opened 2015-08-20 19:53 UTC
**This issue was moved from JIRA to Github**

Originally mentioned by @npwalker : I've run into this a few times in the past but the current issue I have is that I'd like to use https://docs.puppetlabs.com/pe/latest/r10k_config_answers.html but the only way to add those answers is to specify a new answers file which is not sustainable in the long term.  

I think the best general purpose solution would be to allow for specifying any answers in a file or in the config files that would allow for appending to the end of the file or overwriting existing answers.
If not allowing overwriting existing answers which is likely more work, then we should at least allow for appending extra answers to the end of the answers file.  

https://github.com/oscar-stack/vagrant-pe_build/blob/03b93e80220ab0a14a761d4d1df7d5d75e63e6d7/lib/pe_build/provisioner/pe_bootstrap/answers_file.rb

@reidmv states:  Reviewed in TSE Triage, we agree this would be a desirable functionality as long as answer files are bash scripts. It's not a high priority for TSEs specifically though.

**Comment by Sharpie** [comment] 2015-08-22 21:55
I opened issue #66 for this a while ago --- the idea there was to add a new configuration option, such as `override_answers`, that takes a hash:

```
provisioner. override_answers = {
  'q_some_answer' => 'some value',
  'q_some_other_answer => '<%= some_interpolated_value %>'
}
```

This hash would be merged into the templated answer file.

Marking as a duplicate of Issue #66.

**Closed by Sharpie** 2015-08-22 21:55 UTC
